version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
